<style>
    span.material-icons {
        color: var(--poli-green-dark);
        font-size: 4em !important;
        vertical-align: middle;
    }

    .card {
        border: 2px solid #919191;
    }
</style>
<div class="m-3">
    <div class="row row-cols-2">
        <div class="col">
            <a href="#">
                <div class="card">
                    <div class="card-body p-2 text-center">
                        <span class="material-icons">
                            sports_esports
                        </span>
                        <p>Actividades</p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col">
            <a href="#">
                <div class="card">
                    <div class="card-body p-2 text-center">
                        <span class="material-icons">
                            language
                        </span>
                        <p class="text-center">Mis movilidades</p>
                    </div>
                </div>
            </a>
        </div>
        <div class="col mt-3">
            <a href="#">
                <div class="card">
                    <div class="card-body p-2 text-center">
                        <span class="material-icons">
                            grade
                        </span>
                        <p>Recomendaciones</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</div>