
<div class="m-3">
    <p class="note note-info">
        <strong>Tip:</strong>  En esta sección podrás ver el listado de Convenios y Redes vigentes.
            
    </p>
</div>


<ul class="nav nav-tabs" id="myTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link active" id="agreements-tab" data-toggle="tab" href="#agreements" role="tab" aria-controls="agreements"
      aria-selected="true">Convenios</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="networks-tab" data-toggle="tab" href="#networks" role="tab" aria-controls="networks"
      aria-selected="false">Redes</a>
  </li>
</ul>
<div class="m-3 tab-content" id="myTabContent">
  <div class="tab-pane fade show active" id="agreements" role="tabpanel" aria-labelledby="agreements-tab">
    <table id="dtMaterialDesignExample" class="table" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th class="text-center">Tipo</th>
                <th class="text-center">Lugar</th>
                <th class="text-center">Descripción</th>
            </tr>
        </thead>
        <tbody>
            <?php if(count($agreementReport) > 0){
                foreach($agreementReport as $element): ?>
                <tr>
                    <td class="text-center"><?php echo $element->Type?></td>
                    <td class="text-center"><?php echo $element->LocationCity?></td>
                    <td class="text-center"><?php echo $element->PurposeDescription?></td>
                </tr>
            <?php endforeach; } ?>    
        </tbody>
    </table>   
  </div>
  <div class="tab-pane fade" id="networks" role="tabpanel" aria-labelledby="networks-tab">
    <table id="dtMaterialDesignExample" class="table" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th class="text-center">Código</th>
                <th class="text-center">Fecha</th>
                <th class="text-center">Destino</th>
            </tr>
        </thead>
        <tbody>
            <?php if(count($networkReport) > 0){
                foreach($networkReport as $element): ?>
                <tr>
                    <td class="text-center"><?php echo $element->Name?></td>
                    <td class="text-center"><?php echo $element->Type?></td>
                    <td class="text-center"><?php echo $element->SchoolDepartment?></td>
                </tr>
            <?php endforeach; } ?>    
        </tbody>
    </table>
  </div>
</div>




