<style>
    h5.title,
    .main-title span.material-icons {
        color: var(--poli-green-dark) !important;
        font-size: 2.5em;
    }

    .card {
        background: #dbdbdb;
        width: 165px;
        height: 50px;
        margin: 5px 3px;
        border-radius: 20px;
        border-top-left-radius: 30px;
        border-bottom-left-radius: 30px;
    }

    .card h2 {
        font-weight: 600;
        font-size: 1.2em;
        margin-left: 2.8em;
        line-height: 2.5;
        vertical-align: middle;
    }

    .circle {
        border-radius: 100%;
        background: var(--poli-green-dark) !important;
        width: 50px;
        height: 50px;
        position: absolute;
        left: 0px;
        text-align: center;
    }

    .circle span {
        color: #fff;
        font-size: 2em;
        font-weight: 600;
    }
</style>

<div class="container">
    <div class="main-title text-center mb-4">
        <h5 class="title">¿Cómo vamos?</h5>
        <span class="material-icons">
            language
        </span>
    </div>
    <div class="row row-cols-2 d-flex justify-content-center">
        <div class="col p-0">
            <div class="card">
                <h2>Convenios</h2>
                <div class="circle">
                    <span>28</span>
                </div>
            </div>
        </div>
        <div class="col p-0">
            <div class="card">
                <h2>Redes</h2>
                <div class="circle">
                    <span>32</span>
                </div>
            </div>
        </div>
        <div class="col mx-auto p-0">
            <div class="card">
                <h2>Movilidades</h2>
                <div class="circle">
                    <span>28</span>
                </div>
            </div>
        </div>
    </div>
    <div class="date mx-auto text-center m-3">
        <small><em>2020-06-01 hasta 2020-09-01</em></small>
    </div>
    <div class="form-group">
        <label class="d-block">Países</label>
        <select class="form-control">
            <option value="" disabled selected>Todos</option>
        </select>
    </div>
    <div class="universities">
        <div class="row">
            <div class="col-10">
                <a href="#">Universisdad Nacional de Colombia</a>
            </div>
            <div class="col">
                <span class="material-icons">
                    keyboard_arrow_right
                </span>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-10">
                <a href="#">Universisdad Nacional Autónoma de México</a>
            </div>
            <div class="col">
                <span class="material-icons">
                    keyboard_arrow_right
                </span>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-10">
                <a href="#">Universisdad Nacional de Mar del Plata</a>
            </div>
            <div class="col">
                <span class="material-icons">
                    keyboard_arrow_right
                </span>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-10">
                <a href="#">Universisdad de Antioquía</a>
            </div>
            <div class="col">
                <span class="material-icons">
                    keyboard_arrow_right
                </span>
            </div>
        </div>
        <hr>
    </div>
</div>