<style>
    .network-profile {
        margin: 10px;
    }

    .btn-subscribe:hover,
    .btn-subscribe {
        background-color: var(--poli-green-dark) !important;
        color: #fff;
        font-size: 0.8em;
        padding: 7px;
        margin: 5px 0 0 0;
    }

    small {
        font-size: 0.8em;
    }

    .network-profile hr {
        width: 80%;
        border: 1px solid #c7c7c7;
    }
    .popover{
        transform: translate3d(31px, 222px, 0px)!important;
    }

</style>

<div class="network-profile">
    <div class="row">
        <div class="col-2">
            <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(31).jpg" class="rounded-circle" height="60">
        </div>
        <div class="col">
            <h5 class="name m-0">Adriana Portocarrero</h5>
            <small>Directora | Dirección Cooperación Nacional E Internacional</small>
            <button class="btn btn-subscribe d-block" id="myNetwork_subscribe_btn_0">Subscribirme</button>
        </div>
    </div>
    <hr>
</div>

<div class="network-profile">
    <div class="row">
        <div class="col-2">
            <img src="https://mdbootstrap.com/img/Photos/Avatars/img%20(31).jpg" class="rounded-circle" height="60">
        </div>
        <div class="col">
            <h5 class="name m-0">Docente demo</h5>
            <small>Docente | Facultad de Ingeniería</small>
            <button class="btn btn-subscribe d-block">Subscribirme</button>
        </div>
    </div>
    <hr>
</div>

<script>
    $(document).ready(function() {
        new Tooltip().show({
            type: 'myNetwork',
            position: 1
        });
    });
</script>