<!DOCTYPE html>
<html>
    <head>
        <meta name="theme-color" content="#196844" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Cooperemos App | POLI JIC</title>
        
        <!-- Font Awesome -->
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
        <!-- Google Fonts -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap">
        
        <link href="https://fonts.googleapis.com/css2?family=Asap:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;400;500;600;700&display=swap" rel="stylesheet">
        <!-- Bootstrap core CSS -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" rel="stylesheet">
        <!-- Material Design Bootstrap -->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/css/mdb.min.css" rel="stylesheet">
                
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <?php $this->assets->outputCss('headercss');?>

        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.png')?>"/>
    </head>
    <body>
        <div class="container">
            <?php echo $this->getContent(); ?>
        </div>

        <!-- <nav class="nav">
            <a href="#" class="nav__link">
                <i class="material-icons nav__icon">dashboard</i>
                <span class="nav__text">Dashboard</span>
            </a>
            <a href="#" class="nav__link nav__link--active">
                <i class="material-icons nav__icon">person</i>
                <span class="nav__text">Profile</span>
            </a>
            <a href="#" class="nav__link">
                <i class="material-icons nav__icon">devices</i>
                <span class="nav__text">Devices</span>
            </a>
            <a href="#" class="nav__link">
                <i class="material-icons nav__icon">lock</i>
                <span class="nav__text">Privacy</span>
            </a>
            <a href="#" class="nav__link">
                <i class="material-icons nav__icon">settings</i>
                <span class="nav__text">Settings</span>
            </a>
        </nav> -->
       
        <!-- JQuery -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <!-- Bootstrap tooltips -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.4/umd/popper.min.js"></script>
        <!-- Bootstrap core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/js/bootstrap.min.js"></script>
        <!-- MDB core JavaScript -->
        <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdbootstrap/4.19.1/js/mdb.min.js"></script>  
    
    </body>
</html>
